version: "3.9"

services:
  api:
    platform: linux/amd64  # Force compatibility with Windows/WSL
    build:
      context: .
      dockerfile: ToDoApp.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=host.docker.internal,1433;Initial Catalog=SBU-ToDoAppDb;User ID=newuser;Password=12345678;Encrypt=False;TrustServerCertificate=True;

  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ToDoApp.Mvc/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://api:5000/api
    depends_on:
      - api
